services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5052:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/weatherforecast"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nebulift-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NITRO_PRESET=node_server

    networks:
      - nebulift-network

networks:
  nebulift-network:
    driver: bridge
