name: Deploy Nebulift

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    env:
      AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v4

      # Connection to Azure (OIDC)
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploys backend on Azure Web App
      - name: Deploys backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ vars.AZURE_REGISTRY_LOGIN_SERVER }}/nebulift-backend:latest

      # Deploys frontend on Azure Static Site
      - name: Build and deploy app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'frontend/'
          output_location: 'build'
          app_build_command: 'pnpm run build'