name: Nebulift CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Docker build and push
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
    env:
      AZURE_WEBAPP_PACKAGE_PATH: './api'
      
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # Build Backend Docker Image
      - name: Build Backend Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/nebulift-backend:${{ github.sha }} ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Push Backend Docker Image to Azure
      - name: Push Backend Docker Image
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/nebulift-backend:${{ github.sha }}
