name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' 

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.x'

    - name: Install pnpm
      run: npm install -g pnpm

  backend:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build .NET project
      run: dotnet run
      working-directory: ./api

  frontend:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js dependencies
      run: pnpm install
      working-directory: ./frontend

    - name: Build Nuxt project
      run: pnpm run build
      working-directory: ./frontend

    - name: Start Nuxt project
      run: pnpm run preview
      working-directory: ./frontend