# .github/workflows/azure-pipeline.yml
name: Build and Deploy Nebulift

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    steps:
      - uses: actions/checkout@v4

      # Configuration .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build Backend
      - name: Build Backend
        run: |
          cd backend
          dotnet publish src/Nebulift.Api/Nebulift.Api.csproj -c Release -o ../api

      # Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Installation de PNPM globalement
      - name: Install PNPM
        run: npm install -g pnpm

      # Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          pnpm install
          pnpm run build
          
      # Déploiement via Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "api"
          output_location: ".output/public"
          skip_app_build: true 