name: Front CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - name: Install pnpm
      run: npm i -g pnpm
        
    - name: Install dependencies
      run: pnpm i
      working-directory: ./frontend

    - name: Build application
      run: pnpm run build
      working-directory: ./frontend

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: frontend/.output
