
name: Front CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4
    
      - name: 'Download front-end artifact'
        id: download-front-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: front-ci.yml
          workflow_conclusion: completed
          name: artifact

      # Deploys frontend on Azure Static Site
      - name: Build and deploy app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          skip_app_build: true
          action: 'upload'
          app_location: '.'
          output_location: ''