name: Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  infra:
    runs-on: ubuntu-latest
    name: Pulumi up
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}

    defaults:
      run:
        working-directory: infra

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
  
      # Pulumi up
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: teachingiac/nebulift/dev
          work-dir: infra
        env:
          ARM_USE_OIDC: true
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}