name: Nebulift Infra Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true

jobs:
  infra:
    runs-on: ubuntu-latest
    name: Pulumi up
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}
      
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
  
      # Change to infra directory
      - name: Change to infra directory
        run: cd infra
  
      # Select Pulumi stack
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ vars.PULUMI_STACK }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}