name: Nebulift Infra Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true

jobs:
  infra:
    runs-on: ubuntu-latest
    name: Pulumi up
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}

    defaults:
      run:
        working-directory: infra

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Connection to Azure (OIDC)
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      # Pulumi up
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: teachingiac/nebulift/dev
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
