name: Nebulift Infra Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true

jobs:
  infra:
    runs-on: ubuntu-latest
    name: Docker build and push
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'development' }}
    env:
      AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
      AZURE_WEBAPP_PACKAGE_PATH: './api'
      
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Install Pulumi
      - name: Install Pulumi
        uses: pulumi/action-install-pulumi@v1.0.0

      # Set Pulumi access token
      - name: Set Pulumi access token
        run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV
  
      # Change to infra directory
      - name: Change to infra directory
        run: cd infra
  
      # Select Pulumi stack
      - name: Select Pulumi stack
        run: pulumi stack select dev
  
      # Run Pulumi
      - name: Run Pulumi
        run: pulumi up --yes