name: Nebulift Infra Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true

jobs:
  infra:
    runs-on: ubuntu-latest
    name: Pulumi up
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'production' }}

    defaults:
      run:
        working-directory: infra

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Run ls and log the output
      - name: List files in the workspace
        run: |
          echo "Listing files in the workspace:"
          ls -la
          ls -la > ls_output.log  # Save output to a log file
          cat ls_output.log       # Show the log file contents in the action logs
  
      # Pulumi up
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: teachingiac/nebulift/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
